"""
Spyne Application Configuration.

This module creates and configures the Spyne Application object.
The Application ties together:
- Service classes (business logic)
- Protocol configuration (SOAP 1.1)
- Namespace and WSDL settings

WSDL (Web Services Description Language):
The WSDL is automatically generated by Spyne and describes:
- Available operations (methods)
- Input/output message formats
- Data types (ComplexModels)
- Endpoint URL and binding

Access WSDL at: http://localhost:8000/?wsdl
"""
from spyne import Application
from spyne.protocol.soap import Soap11
from spyne.server.wsgi import WsgiApplication

from .service import LibraryCatalogService
from ..config import SERVICE_NAME, SERVICE_NAMESPACE


def create_soap_application() -> WsgiApplication:
    """
    Create and configure the Spyne SOAP Application.

    Returns a WSGI-compatible application that can be served
    by any WSGI server (built-in wsgiref, Gunicorn, uWSGI, etc.)

    Configuration:
    - Services: LibraryCatalogService (our main service)
    - Target namespace: http://library.example.com/catalog
    - Protocol: SOAP 1.1 with lxml validation
    """
    # Create the Spyne Application
    application = Application(
        # List of service classes to expose
        # Multiple services can be exposed from the same application
        services=[LibraryCatalogService],

        # Target namespace for the service
        # This appears in the WSDL and XML namespaces
        # Convention: use your domain name reversed
        tns=SERVICE_NAMESPACE,

        # Service name as it appears in WSDL
        # This is what SoapUI will show as the service name
        name=SERVICE_NAME,

        # Input protocol configuration
        # Soap11 = SOAP 1.1 (most common, widely supported)
        # validator='lxml' enables XML schema validation of requests
        in_protocol=Soap11(validator='lxml'),

        # Output protocol configuration
        # pretty_print=True makes responses human-readable (good for debugging)
        out_protocol=Soap11(pretty_print=True)
    )

    # Wrap in WSGI application
    # This makes it compatible with standard Python web servers
    return WsgiApplication(application)


def get_wsdl_url(host: str, port: int) -> str:
    """
    Generate the WSDL URL for documentation.

    The WSDL URL is the endpoint URL with ?wsdl query parameter.
    SoapUI uses this URL to import the service definition.
    """
    return f'http://{host}:{port}/?wsdl'
